
package torpedo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ITorpedo", targetNamespace = "http://itlabor/torpedo", wsdlLocation = "file:/E:/Workspace/Java/ITLabor2_IIT1/wsdl/TorpedoEndpoint.wsdl")
public class ITorpedo_Service
    extends Service
{

    private final static URL ITORPEDO_WSDL_LOCATION;
    private final static WebServiceException ITORPEDO_EXCEPTION;
    private final static QName ITORPEDO_QNAME = new QName("http://itlabor/torpedo", "ITorpedo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/Workspace/Java/ITLabor2_IIT1/wsdl/TorpedoEndpoint.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITORPEDO_WSDL_LOCATION = url;
        ITORPEDO_EXCEPTION = e;
    }

    public ITorpedo_Service() {
        super(__getWsdlLocation(), ITORPEDO_QNAME);
    }

    public ITorpedo_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITORPEDO_QNAME, features);
    }

    public ITorpedo_Service(URL wsdlLocation) {
        super(wsdlLocation, ITORPEDO_QNAME);
    }

    public ITorpedo_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITORPEDO_QNAME, features);
    }

    public ITorpedo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ITorpedo_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITorpedo
     */
    @WebEndpoint(name = "ITorpedo_Soap11Http_Port")
    public ITorpedo getITorpedoSoap11HttpPort() {
        return super.getPort(new QName("http://itlabor/torpedo", "ITorpedo_Soap11Http_Port"), ITorpedo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITorpedo
     */
    @WebEndpoint(name = "ITorpedo_Soap11Http_Port")
    public ITorpedo getITorpedoSoap11HttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://itlabor/torpedo", "ITorpedo_Soap11Http_Port"), ITorpedo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITORPEDO_EXCEPTION!= null) {
            throw ITORPEDO_EXCEPTION;
        }
        return ITORPEDO_WSDL_LOCATION;
    }

}
