
package torpedo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITorpedo", targetNamespace = "http://itlabor/torpedo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITorpedo {


    /**
     * 
     * @param i
     * @param j
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://itlabor/torpedo/ITorpedo/shot")
    @WebResult(name = "shotResult", targetNamespace = "http://itlabor/torpedo")
    @RequestWrapper(localName = "shot", targetNamespace = "http://itlabor/torpedo", className = "torpedo.Shot")
    @ResponseWrapper(localName = "shotResponse", targetNamespace = "http://itlabor/torpedo", className = "torpedo.ShotResponse")
    public boolean shot(
        @WebParam(name = "i", targetNamespace = "http://itlabor/torpedo")
        int i,
        @WebParam(name = "j", targetNamespace = "http://itlabor/torpedo")
        int j);

}
